### ISSUE TITLE
Proot error when try to run startfedora

### ISSUE THREAD

**Issue by iantothecore** [nmilosev/termux-fedora#20]
Installed termux-fedora without error but when try to run its give proot error, not sure if this proot related error. I'm running android nougat with arm64 architechture. Error attached : https://pasteboard.co/GRJl28p.png

**Comment by iantothecore** [comment]
Got this fixed by put : unset LD_PRELOAD in startfedora ;)

**Comment by nmilosev** [comment]
Interesting, any clue on why this is?

**Comment by PotcFdk** [comment]
Can confirm that this worked for me and that the bug is still present in the current version.
Why is this issue closed?

**Comment by moohamed15** [comment]
I can't star with fedora please correct prblm

**Comment by winDCz** [comment]
put:unset LD_PRELOAD
and it works!Thank you!
